Revert "sched/topology: Optimize topology_span_sane()"
This reverts commit c89cff098550dbfd43240f8b167044ef4e1cff7d.

In file included from ../kernel/sched/build_utility.c:89:
../kernel/sched/topology.c:2219:2: error: call to undeclared function 'for_each_cpu_from'; ISO C99 and later do not support implicit function declarations [-Wimplicit-function-declaration]
 2219 |         for_each_cpu_from(i, cpu_map) {
      |         ^
../kernel/sched/topology.c:2219:31: error: expected ';' after expression
 2219 |         for_each_cpu_from(i, cpu_map) {
      |                                      ^
      |                                      ;
2 errors generated.
make[4]: *** [../scripts/Makefile.build:255: kernel/sched/build_utility.o] Error 1
make[3]: *** [../scripts/Makefile.build:520: kernel/sched] Error 2
make[2]: *** [../scripts/Makefile.build:520: kernel] Error 2